# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 600)
        MainWindow.setMinimumSize(QtCore.QSize(200, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_header_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.main_header_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header_frame.setStyleSheet("background-color: #0C0A63;\n"
"border-bottom: 2px solid black;")
        self.main_header_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header_frame.setObjectName("main_header_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.main_header_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_menu_toggle = QtWidgets.QFrame(self.main_header_frame)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(150, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(150, 16777215))
        self.left_menu_toggle.setStyleSheet("QPushButton\n"
"{\n"
"border: none;\n"
"color: #fff;\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: #0C0A6f;\n"
"}")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggleButton = QtWidgets.QPushButton(self.left_menu_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_menu_toggleButton.sizePolicy().hasHeightForWidth())
        self.left_menu_toggleButton.setSizePolicy(sizePolicy)
        self.left_menu_toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.left_menu_toggleButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/white_icons/customized/list_menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_menu_toggleButton.setIcon(icon)
        self.left_menu_toggleButton.setIconSize(QtCore.QSize(32, 32))
        self.left_menu_toggleButton.setFlat(False)
        self.left_menu_toggleButton.setObjectName("left_menu_toggleButton")
        self.horizontalLayout_5.addWidget(self.left_menu_toggleButton)
        self.onoff_frame = QtWidgets.QFrame(self.left_menu_toggle)
        self.onoff_frame.setStyleSheet("border: no-border;")
        self.onoff_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.onoff_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.onoff_frame.setLineWidth(0)
        self.onoff_frame.setObjectName("onoff_frame")
        self.horizontalLayout_5.addWidget(self.onoff_frame)
        self.horizontalLayout_3.addWidget(self.left_menu_toggle)
        self.right_header = QtWidgets.QFrame(self.main_header_frame)
        self.right_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_header.setObjectName("right_header")
        self.horizontalLayout_3.addWidget(self.right_header)
        self.verticalLayout.addWidget(self.main_header_frame)
        self.body_frame = QtWidgets.QFrame(self.centralwidget)
        self.body_frame.setStyleSheet("/*.QFrame {\n"
"border: none;\n"
"}*/")
        self.body_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.body_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_bar_frame = QtWidgets.QFrame(self.body_frame)
        self.menu_bar_frame.setMinimumSize(QtCore.QSize(50, 0))
        self.menu_bar_frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_bar_frame.setStyleSheet("background-color: #0C0A63;")
        self.menu_bar_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_bar_frame.setObjectName("menu_bar_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.menu_bar_frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.upper_menu_bar = QtWidgets.QFrame(self.menu_bar_frame)
        self.upper_menu_bar.setStyleSheet("QPushButton\n"
"{\n"
"text-align: right;\n"
"border-top-left-radius: 8px;\n"
"border-bottom-left-radius: 12px;\n"
"background-color: #0C0A63;\n"
"color: #fff;\n"
"font-size: 14px;\n"
"/*margin: 7px 0;*/\n"
"/*padding: 10px 5px;*/\n"
"padding: 10px 12px 10px 40px;\n"
"\n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: #0Cf;\n"
"}\n"
"")
        self.upper_menu_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.upper_menu_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upper_menu_bar.setObjectName("upper_menu_bar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.upper_menu_bar)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setSpacing(14)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.effectsButton = QtWidgets.QPushButton(self.upper_menu_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effectsButton.sizePolicy().hasHeightForWidth())
        self.effectsButton.setSizePolicy(sizePolicy)
        self.effectsButton.setMinimumSize(QtCore.QSize(150, 0))
        self.effectsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effectsButton.setStyleSheet("background-image: url(:/white_icons/customized/cil-lightbulb.png);\n"
"\n"
"border-bottom: 2px solid red;\n"
"border-left: 2px solid red;")
        self.effectsButton.setIconSize(QtCore.QSize(48, 16))
        self.effectsButton.setObjectName("effectsButton")
        self.verticalLayout_4.addWidget(self.effectsButton)
        self.paintButton = QtWidgets.QPushButton(self.upper_menu_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paintButton.sizePolicy().hasHeightForWidth())
        self.paintButton.setSizePolicy(sizePolicy)
        self.paintButton.setMinimumSize(QtCore.QSize(150, 0))
        self.paintButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paintButton.setStyleSheet("background-image: url(:/white_icons/customized/white_brush-icon.png);")
        self.paintButton.setObjectName("paintButton")
        self.verticalLayout_4.addWidget(self.paintButton)
        self.commandsButton = QtWidgets.QPushButton(self.upper_menu_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandsButton.sizePolicy().hasHeightForWidth())
        self.commandsButton.setSizePolicy(sizePolicy)
        self.commandsButton.setMinimumSize(QtCore.QSize(150, 0))
        self.commandsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandsButton.setStyleSheet("background-image: url(:/white_icons/customized/cil-terminal.png);")
        self.commandsButton.setFlat(False)
        self.commandsButton.setObjectName("commandsButton")
        self.verticalLayout_4.addWidget(self.commandsButton)
        self.verticalLayout_9.addWidget(self.upper_menu_bar, 0, QtCore.Qt.AlignTop)
        self.lower_menu_bar = QtWidgets.QFrame(self.menu_bar_frame)
        self.lower_menu_bar.setStyleSheet("")
        self.lower_menu_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lower_menu_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lower_menu_bar.setObjectName("lower_menu_bar")
        self.verticalLayout_9.addWidget(self.lower_menu_bar)
        self.horizontalLayout.addWidget(self.menu_bar_frame)
        self.content_area_frame = QtWidgets.QFrame(self.body_frame)
        self.content_area_frame.setStyleSheet("background-color: #063C70;\n"
"/*background-color: #02007D;*/")
        self.content_area_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_area_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_area_frame.setObjectName("content_area_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_area_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.content_frame = QtWidgets.QFrame(self.content_area_frame)
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.content = QtWidgets.QStackedWidget(self.content_frame)
        self.content.setStyleSheet("")
        self.content.setObjectName("content")
        self.effects_page = QtWidgets.QWidget()
        self.effects_page.setObjectName("effects_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.effects_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.effects_frame = QtWidgets.QFrame(self.effects_page)
        self.effects_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.effects_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.effects_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.effects_frame.setObjectName("effects_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.effects_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.effect1_frame_2 = QtWidgets.QFrame(self.effects_frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.effect1_frame_2.setPalette(palette)
        self.effect1_frame_2.setStyleSheet("")
        self.effect1_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.effect1_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.effect1_frame_2.setObjectName("effect1_frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.effect1_frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.effect1_active = QtWidgets.QCheckBox(self.effect1_frame_2)
        self.effect1_active.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effect1_active.setStyleSheet("color: #fff;")
        self.effect1_active.setObjectName("effect1_active")
        self.verticalLayout_7.addWidget(self.effect1_active)
        self.effect1_choose_frame = QtWidgets.QFrame(self.effect1_frame_2)
        self.effect1_choose_frame.setStyleSheet("")
        self.effect1_choose_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.effect1_choose_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.effect1_choose_frame.setObjectName("effect1_choose_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.effect1_choose_frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.effect1_choose_combobox = QtWidgets.QComboBox(self.effect1_choose_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect1_choose_combobox.sizePolicy().hasHeightForWidth())
        self.effect1_choose_combobox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.effect1_choose_combobox.setPalette(palette)
        self.effect1_choose_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effect1_choose_combobox.setStyleSheet("QComboBox {\n"
"color: #fff;\n"
"padding: 4px 10px;\n"
"border: 2px solid #007D76;\n"
"background-color: #007899;\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}\n"
"/*QComboBox::drop-down{\n"
"image: url(:/white_icons/customized/white_arrow_down2.png);\n"
"}*/\n"
"QComboBox::down-arrow{\n"
"image: url(:/white_icons/customized/white_arrow_down2.png);\n"
"top: 1px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 24px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"}\n"
"QComboBox:hover {\n"
"background-color: #008AB0;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"background-color: #008ADF;\n"
"border-radius: 12px;\n"
"}\n"
"QComboBox:on{\n"
"padding-left: 5px;\n"
"}\n"
"QComboBox::drop-down:on {\n"
"top: 3px;\n"
"}\n"
"QComoBox QAbstractItemView {\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}")
        self.effect1_choose_combobox.setCurrentText("")
        self.effect1_choose_combobox.setPlaceholderText("")
        self.effect1_choose_combobox.setFrame(True)
        self.effect1_choose_combobox.setObjectName("effect1_choose_combobox")
        self.horizontalLayout_9.addWidget(self.effect1_choose_combobox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.effect1_customizeButton = QtWidgets.QPushButton(self.effect1_choose_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect1_customizeButton.sizePolicy().hasHeightForWidth())
        self.effect1_customizeButton.setSizePolicy(sizePolicy)
        self.effect1_customizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effect1_customizeButton.setStyleSheet("QPushButton {\n"
"color: rgb(240, 240, 240);\n"
"padding: 4px 10px;\n"
"border: 2px solid #007D76;\n"
"background-color: #007899;\n"
"/*border-radius: 8px;*/\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008AB0;\n"
"}")
        self.effect1_customizeButton.setObjectName("effect1_customizeButton")
        self.horizontalLayout_9.addWidget(self.effect1_customizeButton)
        self.verticalLayout_7.addWidget(self.effect1_choose_frame)
        self.effect1_summary = QtWidgets.QTreeView(self.effect1_frame_2)
        self.effect1_summary.setStyleSheet("QTreeView::item\n"
"{\n"
"text-align: right;\n"
"}\n"
"QCheckBox {\n"
"float: right; }")
        self.effect1_summary.setObjectName("effect1_summary")
        self.verticalLayout_7.addWidget(self.effect1_summary)
        self.horizontalLayout_8.addWidget(self.effect1_frame_2)
        self.effect2_frame = QtWidgets.QFrame(self.effects_frame)
        self.effect2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.effect2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.effect2_frame.setObjectName("effect2_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.effect2_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.effect2_active = QtWidgets.QCheckBox(self.effect2_frame)
        self.effect2_active.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effect2_active.setStyleSheet("color: #fff;")
        self.effect2_active.setObjectName("effect2_active")
        self.verticalLayout_8.addWidget(self.effect2_active)
        self.effect2_choose_frame = QtWidgets.QFrame(self.effect2_frame)
        self.effect2_choose_frame.setStyleSheet("")
        self.effect2_choose_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.effect2_choose_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.effect2_choose_frame.setObjectName("effect2_choose_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.effect2_choose_frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.effect2_choose_combobox = QtWidgets.QComboBox(self.effect2_choose_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect2_choose_combobox.sizePolicy().hasHeightForWidth())
        self.effect2_choose_combobox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.effect2_choose_combobox.setPalette(palette)
        self.effect2_choose_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effect2_choose_combobox.setStyleSheet("QComboBox {\n"
"color: #fff;\n"
"padding: 4px 10px;\n"
"border: 2px solid #007D76;\n"
"background-color: #007899;\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}\n"
"/*QComboBox::drop-down{\n"
"image: url(:/white_icons/customized/white_arrow_down2.png);\n"
"}*/\n"
"QComboBox::down-arrow{\n"
"image: url(:/white_icons/customized/white_arrow_down2.png);\n"
"top: 1px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 24px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"}\n"
"QComboBox:hover {\n"
"background-color: #008AB0;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"background-color: #008ADF;\n"
"border-radius: 12px;\n"
"}\n"
"QComboBox:on{\n"
"padding-left: 5px;\n"
"}\n"
"QComboBox::drop-down:on {\n"
"top: 3px;\n"
"}\n"
"QComoBox QAbstractItemView {\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}")
        self.effect2_choose_combobox.setCurrentText("")
        self.effect2_choose_combobox.setPlaceholderText("")
        self.effect2_choose_combobox.setFrame(True)
        self.effect2_choose_combobox.setObjectName("effect2_choose_combobox")
        self.horizontalLayout_10.addWidget(self.effect2_choose_combobox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.effect2_customizeButton = QtWidgets.QPushButton(self.effect2_choose_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect2_customizeButton.sizePolicy().hasHeightForWidth())
        self.effect2_customizeButton.setSizePolicy(sizePolicy)
        self.effect2_customizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effect2_customizeButton.setStyleSheet("QPushButton {\n"
"color: rgb(240, 240, 240);\n"
"padding: 4px 10px;\n"
"border: 2px solid #007D76;\n"
"background-color: #007899;\n"
"/*border-radius: 8px;*/\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008AB0;\n"
"}")
        self.effect2_customizeButton.setObjectName("effect2_customizeButton")
        self.horizontalLayout_10.addWidget(self.effect2_customizeButton)
        self.verticalLayout_8.addWidget(self.effect2_choose_frame)
        self.effect2_summary = QtWidgets.QTreeView(self.effect2_frame)
        self.effect2_summary.setObjectName("effect2_summary")
        self.verticalLayout_8.addWidget(self.effect2_summary)
        self.horizontalLayout_8.addWidget(self.effect2_frame)
        self.verticalLayout_6.addWidget(self.effects_frame)
        self.effect1_frame = QtWidgets.QFrame(self.effects_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect1_frame.sizePolicy().hasHeightForWidth())
        self.effect1_frame.setSizePolicy(sizePolicy)
        self.effect1_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.effect1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.effect1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.effect1_frame.setObjectName("effect1_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.effect1_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.effect1_blend_label = QtWidgets.QLabel(self.effect1_frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.effect1_blend_label.setPalette(palette)
        self.effect1_blend_label.setObjectName("effect1_blend_label")
        self.horizontalLayout_7.addWidget(self.effect1_blend_label)
        self.blend_slider = QtWidgets.QSlider(self.effect1_frame)
        self.blend_slider.setMaximum(255)
        self.blend_slider.setOrientation(QtCore.Qt.Horizontal)
        self.blend_slider.setInvertedAppearance(False)
        self.blend_slider.setObjectName("blend_slider")
        self.horizontalLayout_7.addWidget(self.blend_slider)
        self.effect2_blend_label = QtWidgets.QLabel(self.effect1_frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 60, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.effect2_blend_label.setPalette(palette)
        self.effect2_blend_label.setObjectName("effect2_blend_label")
        self.horizontalLayout_7.addWidget(self.effect2_blend_label)
        self.verticalLayout_6.addWidget(self.effect1_frame)
        self.content.addWidget(self.effects_page)
        self.full_control_page = QtWidgets.QWidget()
        self.full_control_page.setObjectName("full_control_page")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.full_control_page)
        self.calendarWidget.setGeometry(QtCore.QRect(410, 150, 344, 156))
        self.calendarWidget.setObjectName("calendarWidget")
        self.content.addWidget(self.full_control_page)
        self.commands_page = QtWidgets.QWidget()
        self.commands_page.setObjectName("commands_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.commands_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.console_frame = QtWidgets.QFrame(self.commands_page)
        self.console_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.console_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.console_frame.setObjectName("console_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.console_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.user_input = QtWidgets.QLineEdit(self.console_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.user_input.setFont(font)
        self.user_input.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.user_input.setMaxLength(200)
        self.user_input.setObjectName("user_input")
        self.verticalLayout_2.addWidget(self.user_input)
        self.communication_histoy = QtWidgets.QListView(self.console_frame)
        self.communication_histoy.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.communication_histoy.setObjectName("communication_histoy")
        self.verticalLayout_2.addWidget(self.communication_histoy)
        self.verticalLayout_5.addWidget(self.console_frame)
        self.cheatsheed_frame = QtWidgets.QFrame(self.commands_page)
        self.cheatsheed_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cheatsheed_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cheatsheed_frame.setObjectName("cheatsheed_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.cheatsheed_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.cheatsheed_frame)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.cheatsheed_frame)
        self.content.addWidget(self.commands_page)
        self.horizontalLayout_4.addWidget(self.content)
        self.verticalLayout_3.addWidget(self.content_frame)
        self.main_footer_frame = QtWidgets.QFrame(self.content_area_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_footer_frame.sizePolicy().hasHeightForWidth())
        self.main_footer_frame.setSizePolicy(sizePolicy)
        self.main_footer_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.main_footer_frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.main_footer_frame.setStyleSheet("background-color: #002287;")
        self.main_footer_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer_frame.setObjectName("main_footer_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_footer_frame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_footer_frame = QtWidgets.QFrame(self.main_footer_frame)
        self.left_footer_frame.setMinimumSize(QtCore.QSize(100, 0))
        self.left_footer_frame.setStyleSheet("/*background-color: rgb(170, 255, 0);*/")
        self.left_footer_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_footer_frame.setObjectName("left_footer_frame")
        self.horizontalLayout_2.addWidget(self.left_footer_frame)
        self.right_footer_frame = QtWidgets.QFrame(self.main_footer_frame)
        self.right_footer_frame.setStyleSheet("QPushButton {\n"
"color: rgb(240, 240, 240);\n"
"padding: 4px 10px;\n"
"border: 2px solid #007D76;\n"
"background-color: #007899;\n"
"/*border-radius: 8px;*/\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #008AB0;\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"/*background-color: rgb(0, 255, 0);*/\n"
"}")
        self.right_footer_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_footer_frame.setObjectName("right_footer_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.right_footer_frame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.refresh_usb_portsButton = QtWidgets.QPushButton(self.right_footer_frame)
        self.refresh_usb_portsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_usb_portsButton.setObjectName("refresh_usb_portsButton")
        self.horizontalLayout_11.addWidget(self.refresh_usb_portsButton)
        self.usb_port_list = QtWidgets.QComboBox(self.right_footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usb_port_list.sizePolicy().hasHeightForWidth())
        self.usb_port_list.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.usb_port_list.setPalette(palette)
        self.usb_port_list.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.usb_port_list.setStyleSheet("QComboBox {\n"
"color: #fff;\n"
"padding: 4px 10px;\n"
"border: 2px solid #007D76;\n"
"background-color: #007899;\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}\n"
"/*QComboBox::drop-down{\n"
"image: url(:/white_icons/customized/white_arrow_down2.png);\n"
"}*/\n"
"QComboBox::down-arrow{\n"
"image: url(:/white_icons/customized/white_arrow_down2.png);\n"
"top: 1px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 24px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"}\n"
"QComboBox:hover {\n"
"background-color: #008AB0;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"background-color: #008ADF;\n"
"border-radius: 12px;\n"
"}\n"
"QComboBox:on{\n"
"padding-left: 5px;\n"
"}\n"
"QComboBox::drop-down:on {\n"
"top: 3px;\n"
"}\n"
"QComoBox QAbstractItemView {\n"
"border-top-left-radius: 8px;\n"
"border-bottom-right-radius: 8px;\n"
"}")
        self.usb_port_list.setCurrentText("")
        self.usb_port_list.setPlaceholderText("")
        self.usb_port_list.setFrame(True)
        self.usb_port_list.setObjectName("usb_port_list")
        self.horizontalLayout_11.addWidget(self.usb_port_list)
        self.applyButton = QtWidgets.QPushButton(self.right_footer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyButton.sizePolicy().hasHeightForWidth())
        self.applyButton.setSizePolicy(sizePolicy)
        self.applyButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.applyButton.setStyleSheet("")
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout_11.addWidget(self.applyButton)
        self.horizontalLayout_2.addWidget(self.right_footer_frame)
        self.verticalLayout_3.addWidget(self.main_footer_frame)
        self.horizontalLayout.addWidget(self.content_area_frame)
        self.verticalLayout.addWidget(self.body_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.content.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_menu_toggleButton.setText(_translate("MainWindow", "Menu"))
        self.effectsButton.setText(_translate("MainWindow", "Effects"))
        self.paintButton.setText(_translate("MainWindow", "Paint"))
        self.commandsButton.setText(_translate("MainWindow", "Commands"))
        self.effect1_active.setText(_translate("MainWindow", "Efekt nr 1"))
        self.effect1_customizeButton.setText(_translate("MainWindow", "Customize"))
        self.effect2_active.setText(_translate("MainWindow", "Efekt nr 1"))
        self.effect2_customizeButton.setText(_translate("MainWindow", "Customize"))
        self.effect1_blend_label.setText(_translate("MainWindow", "Efekt nr 1"))
        self.effect2_blend_label.setText(_translate("MainWindow", "Efekt nr 2"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.refresh_usb_portsButton.setText(_translate("MainWindow", "Refresh"))
        self.applyButton.setText(_translate("MainWindow", "Apply"))
from PC_program_src.ui import customized_icons_rc
